# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

coreDualLoop <- function(X, Y, gam_vb, log_Phi_mu_theta_plus_zeta, log_1_min_Phi_mu_theta_plus_zeta, log_sig2_inv_vb, log_tau_vb, beta_vb, X_beta_vb, mu_beta_vb, sig2_beta_vb, tau_vb, shuffled_ind, c = 1) {
    invisible(.Call(`_epispot_coreDualLoop`, X, Y, gam_vb, log_Phi_mu_theta_plus_zeta, log_1_min_Phi_mu_theta_plus_zeta, log_sig2_inv_vb, log_tau_vb, beta_vb, X_beta_vb, mu_beta_vb, sig2_beta_vb, tau_vb, shuffled_ind, c))
}

coreDualInfoLoop <- function(V, W, rho_vb, log_om, log_1_min_om, s2, xi_vb, mat_v_mu, mu_xi_vb, sig2_xi_vb, shuffled_ind, c = 1) {
    invisible(.Call(`_epispot_coreDualInfoLoop`, V, W, rho_vb, log_om, log_1_min_om, s2, xi_vb, mat_v_mu, mu_xi_vb, sig2_xi_vb, shuffled_ind, c))
}

